apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-service

resources:
  - namespace.yaml
  - fastapi-deployment.yaml
  - fastapi-service.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: infra-test-web-service

images:
  - name: web-service-api
    newName: harbor.imcherry5778.xyz/library/web-service-api
    newTag: cabc0292ebc38e05fc893b4c20ab960b958231a0
