apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-service

resources:
  - namespace.yaml
  - fastapi-deployment.yaml
  - fastapi-service.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: infra-test-web-service

images:
  - name: web-service-api
    newName: docker.io/jieun3113/web-service-api
    newTag: "c6f6d5aca805aeafec0e47dc7f69b807f713a810"
